INSERT INTO member(social_provider, social_id, email, name, profile_image_url, nationality, introduction,
                   profile_complete, status, role, type)
VALUES ('GOOGLE', 'ID-MENTEE-1', 'mentee1@gmail.com', 'Le Minh C',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee1.png', 'VIETNAM',
        '안녕하세요, 한국을 좋아하는 학생입니다. 서울대 철학과 편입을 목표로 한국어 공부 및 유학 준비를 하고 있습니다. 한국어, 영어, 베트남어로 대화가 가능합니다! 합격 서류에 대한 자기소개서 질문이 많아요.',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-2', 'mentee2@gmail.com', 'Mizuki Kiyoshi',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee2.png', 'JAPAN',
        '안녕하세요, 도쿄대에 다니고 있는 미즈키입니다. 한국을 너무 좋아해서, (드라마 너무 좋아해요) 졸업하고 대학원 유학을 생각하고 있습니다! 어떤 점이 좋고 어떤 점이 나쁜지에 대해 직접 들어보고 싶습니다. 잘 부탁드립니다!',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-3', 'mentee3@gmail.com', 'Jackson Wang',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee3.png', 'CHINA',
        'Hello, I’m Jackson. I’m studying at Wuhan Engineering school right now, and planning to go to Korea University next year for transfer. If there’s any chinese speaker that can answer my questions it’ll be the best. Thank you!',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-4', 'mentee4@gmail.com', 'Jenny Nelson',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee4.png', 'USA',
        'Hello friends! I’m Jenny from Boston,Massachusetts. I’m currently studying education in Harvard University and am very interested in Ewha Women’s Uni. I might ask a bunch of questions about the women’s uni life in general! Hope to talk to you soon, thanks!',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-5', 'mentee5@gmail.com', 'Saki Nakamura',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee5.png', 'JAPAN',
        '안녕하세요! 한국 유학에 관심이 있는 일본 학생입니다. 아직 한국어가 서툴지만 한국어로 소통하고 싶고, 한국의 대학 생활에 대해 물어보고 싶은 것이 있습니다! 예상 비용이나 거주 지역과 같은 것들이 가장 궁금합니다.',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-6', 'mentee6@gmail.com', 'Nguyen Nam',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee6.png', 'VIETNAM',
        'Hello, I’m a Vietnamese student who is currently studying in CUNY, New York. I’m planning my study abroad to Korea and Seoul City University seems to be a great fit to me. I have some cultural questions to ask as I couldn’t really find relevant info online. Would really appreciate if you spare time to chat with me! ',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-7', 'mentee7@gmail.com', 'Allison Pittman',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee7.png', 'ETC',
        'Hi! I’m Allison from London School of Economics. I’m looking for someone who can guide me through my application docs and want to get to know some of Korean colleagues before going to Korea! Super excited.',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-8', 'mentee8@gmail.com', 'Andrew Harris',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee8.png', 'USA',
        'Hello all! I’m planning to apply to Busan University. I’m from Michigan and can speak basic Korean. It’ll be amazing if we can chat about the Busan life and how it is different from Seoul.',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-9', 'mentee9@gmail.com', 'Wendy Wang',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee9.png', 'JAPAN',
        '韓国留学を準備中の日本人です。 長崎に住んでいて、韓国語は下手です。 韓国語ができなければ生活が難しいか一番悩んでいます。',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-10', 'mentee10@gmail.com', 'Haoyuan Chen',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee10.png', 'CHINA',
        'Chinese exchange student / interested in housing',
        1, 'ACTIVE', 'MENTEE', 'MENTEE');

INSERT INTO mentee(id, interest_school, interest_major)
VALUES (1, '서울대학교', '철학'),
       (2, '연세대학교', '컴퓨터공학'),
       (3, '고려대학교', '전기전자'),
       (4, '이화여자대학교', '유아교육'),
       (5, '경희대학교', '심리학'),
       (6, '서울시립대학교', '체육'),
       (7, '청주대학교', '경제'),
       (8, '부산대학교', '전기전자'),
       (9, '경기대학교', '생명과학'),
       (10, '서울시립대학교', '국제관계');
