server:
  tomcat:
    mbeanregistry:
      enabled: true
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koddy?autoReconnect=true&characterEncoding=UTF8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 50

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET:s3-bucket}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

  web:
    resources:
      add-mappings: false

oauth2:
  google:
    grant-type: authorization_code
    client-id: ${OAUTH_GOOGLE_CLIENT_ID:google-cliend-id}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:google-client-secret}
    redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI:google-client-redirect-uri}
    scope:
      - openid
      - profile
      - email
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    token-url: https://www.googleapis.com/oauth2/v4/token
    user-info-url: https://www.googleapis.com/oauth2/v3/userinfo
  kakao:
    grant-type: authorization_code
    client-id: ${OAUTH_KAKAO_CLIENT_ID:kakao-client-id}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:kakao-client-secret}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI:kakao-redirect-uri}
    scope:
      - profile_nickname
      - profile_image
      - account_email
    auth-url: https://kauth.kakao.com/oauth/authorize
    token-url: https://kauth.kakao.com/oauth/token
    user-info-url: https://kapi.kakao.com/v2/user/me
  zoom:
    grant-type: authorization_code
    client-id: ${OAUTH_ZOOM_CLIENT_ID:zoom-client-id}
    client-secret: ${OAUTH_ZOOM_CLIENT_SECRET:zoom-client-secret}
    redirect-uri: ${OAUTH_ZOOM_REDIRECT_URI:zoom-redirect-uri}
    auth-url: https://zoom.us/oauth/authorize
    token-url: https://zoom.us/oauth/token
    user-info-url: https://api.zoom.us/v2/users/me
    other:
      create-meeting-url: https://api.zoom.us/v2/users/me/meetings
      delete-meeting-url: https://api.zoom.us/v2/meetings/{meetingId}

cors:
  allowed-origin-patterns: http://localhost:3000

encrypt:
  secret-key: 26f01335335d279cc9fbfa1cb2b73819111460fa21905f689763946b6bf4beee
  salt: 0b7a3890901fe0c61f14f26ab87189211922d4a294f9619bf70606618d6044f3 # Even Hex Number

jwt:
  secret-key: 2da7acad220ffe59e6943c826ec1fcf879a4339521ff5837fa92aab485e94bcb
  access-token-validity-seconds: 7200
  refresh-token-validity-seconds: 1209600

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:slack-webhook-url}

springdoc:
  server:
    url: http://localhost:8080
  swagger-ui:
    path: /api/swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.springframework.core:
      LocalVariableTableParameterNameDiscoverer: error
