server:
  tomcat:
    mbeanregistry:
      enabled: true
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koddy?autoReconnect=true&characterEncoding=UTF8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 50

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET:s3-bucket}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

  web:
    resources:
      add-mappings: false

oauth2:
  google:
    grant-type: authorization_code
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH_GOOGLE_REDIRECT_URI}
    scope: openid, profile, email
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    token-url: https://www.googleapis.com/oauth2/v4/token
    user-info-url: https://www.googleapis.com/oauth2/v3/userinfo
  kakao:
    grant-type: authorization_code
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    scope: profile_nickname, profile_image, account_email
    auth-url: https://kauth.kakao.com/oauth/authorize
    token-url: https://kauth.kakao.com/oauth/token
    user-info-url: https://kapi.kakao.com/v2/user/me

cors:
  allowed-origin-patterns: http://localhost:3000

jwt:
  secret-key: 2da7acad220ffe59e6943c826ec1fcf879a4339521ff5837fa92aab485e94bcb # 테스트용 Secret Key
  access-token-validity-seconds: 7200
  refresh-token-validity-seconds: 1209600

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:slack-webhook-url}

springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.springframework.core:
      LocalVariableTableParameterNameDiscoverer: error
