INSERT INTO member(social_provider, social_id, email, name, nationality, introduction, profile_image_url,
                   profile_complete, status, role, type)
VALUES ('GOOGLE', 'ID-MENTEE-1', 'mentee1@gmail.com', 'Le Minh C', 'VIETNAM',
        '안녕하세요, 한국을 좋아하는 학생입니다. 서울대 철학과 편입을 목표로 한국어 공부 및 유학 준비를 하고 있습니다. 한국어, 영어, 베트남어로 대화가 가능합니다! 합격 서류에 대한 자기소개서 질문이 많아요.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee1.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-2', 'mentee2@gmail.com', 'Mizuki Kiyoshi', 'JAPAN',
        '안녕하세요, 도쿄대에 다니고 있는 미즈키입니다. 한국을 너무 좋아해서, (드라마 너무 좋아해요) 졸업하고 대학원 유학을 생각하고 있습니다! 어떤 점이 좋고 어떤 점이 나쁜지에 대해 직접 들어보고 싶습니다. 잘 부탁드립니다!',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee2.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-3', 'mentee3@gmail.com', 'Jackson Wang', 'CHINA',
        'Hello, I’m Jackson. I’m studying at Wuhan Engineering school right now, and planning to go to Korea University next year for transfer. If there’s any chinese speaker that can answer my questions it’ll be the best. Thank you!',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee3.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-4', 'mentee4@gmail.com', 'Jenny Nelson', 'USA',
        'Hello friends! I’m Jenny from Boston,Massachusetts. I’m currently studying education in Harvard University and am very interested in Ewha Women’s Uni. I might ask a bunch of questions about the women’s uni life in general! Hope to talk to you soon, thanks!',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee4.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-5', 'mentee5@gmail.com', 'Saki Nakamura', 'JAPAN',
        '안녕하세요! 한국 유학에 관심이 있는 일본 학생입니다. 아직 한국어가 서툴지만 한국어로 소통하고 싶고, 한국의 대학 생활에 대해 물어보고 싶은 것이 있습니다! 예상 비용이나 거주 지역과 같은 것들이 가장 궁금합니다.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee5.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-6', 'mentee6@gmail.com', 'Nguyen Nam', 'VIETNAM',
        'Hello, I’m a Vietnamese student who is currently studying in CUNY, New York. I’m planning my study abroad to Korea and Seoul City University seems to be a great fit to me. I have some cultural questions to ask as I couldn’t really find relevant info online. Would really appreciate if you spare time to chat with me! ',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee6.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-7', 'mentee7@gmail.com', 'Allison Pittman', 'ETC',
        'Hi! I’m Allison from London School of Economics. I’m looking for someone who can guide me through my application docs and want to get to know some of Korean colleagues before going to Korea! Super excited.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee7.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-8', 'mentee8@gmail.com', 'Andrew Harris', 'USA',
        'Hello all! I’m planning to apply to Busan University. I’m from Michigan and can speak basic Korean. It’ll be amazing if we can chat about the Busan life and how it is different from Seoul.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee8.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-9', 'mentee9@gmail.com', 'Wendy Wang', 'JAPAN',
        '韓国留学を準備中の日本人です。 長崎に住んでいて、韓国語は下手です。 韓国語ができなければ生活が難しいか一番悩んでいます。',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee9.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE'),
       ('GOOGLE', 'ID-MENTEE-10', 'mentee10@gmail.com', 'Haoyuan Chen', 'CHINA',
        'Chinese exchange student / interested in housing',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentee10.png',
        1, 'ACTIVE', 'MENTEE', 'MENTEE');

INSERT INTO mentee(id, interest_school, interest_major)
VALUES (1, '서울대학교', '철학'),
       (2, '연세대학교', '컴퓨터공학'),
       (3, '고려대학교', '전기전자'),
       (4, '이화여자대학교', '유아교육'),
       (5, '경희대학교', '심리학'),
       (6, '서울시립대학교', '체육'),
       (7, '청주대학교', '경제'),
       (8, '부산대학교', '전기전자'),
       (9, '경기대학교', '생명과학'),
       (10, '서울시립대학교', '국제관계');

INSERT INTO member(social_provider, social_id, email, name, nationality, introduction, profile_image_url,
                   profile_complete, status, role, type)
VALUES ('GOOGLE', 'ID-MENTOR-1', 'mentor1@gmail.com', '김선아', 'KOREA',
        '안녕하세요. 중앙대 패션 디자인 학부 22학번 김선아에요! 한국어·영어 능통하게 소통 가능하며, 멘토로 여러분과 대학 생활 공유하고 즐겁게 지내고 싶어요.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor1.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-2', 'mentor2@gmail.com', '김지원', 'KOREA',
        '안녕하세요, 저는 김지원이라고 합니다. 컴퓨터 공학을 전공으로 공부하고 있는 학생이에요. 학교 글로벌 프로젝트에도 참여하고 있어 학교의 다양한 지원 정책을 알고 있어요',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor2.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-3', 'mentor3@gmail.com', '이민주', 'KOREA',
        '안녕하세요! 저는 건축에 대한 열정으로 창의적인 아이디어와 디자인을 추구하고 있어요. 다양한 배경을 존중하며 소통하는 것을 중요하게 생각해 코띠 멘토로 여러분과 소중한 경험을 나누고 싶어요 🥰✨',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor3.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-4', 'mentor4@gmail.com', '정민호', 'KOREA',
        '안녕하세요! 저는 국민대학교에서 시각디자인을 전공 중인 정민호라고 합니다. 코띠 멘토로 참여한 이유는 외국인 친구들과 소통하며 다양한 문화를 체험하고, 그 과정에서 친구들에게 대학 라이프 꿀팁도 나눠주고 싶어요. 같이 웃고 같이 고민하며, 멘토링 커피챗을 통해 새로운 우정을 만들었으면 좋겠어요! 언제든 제게 커피챗을 신청해주세요. 💪',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor4.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-5', 'mentor5@gmail.com', '송지은', 'KOREA',
        '안녕하세요 서강대 새내기 송지은 입니다. 저희 학과나 학교에 궁금한 점이 있다면 편하게 커피챗 요청해주세요! 일본어를 쓸 기회가 없어서 일본어로 소통하면 너무 좋을 것 같아요~',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor5.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-6', 'mentor6@gmail.com', '홍영호', 'KOREA',
        '동아시아의 다양한 문화와 역사에 관심을 가지고 있어, 학문을 통해 깊게 탐구하고 있어요. 코띠 멘토로 여러분과 문화 교류하며 소중한 경험을 나누고 함께 성장하고 싶어요.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor6.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-7', 'mentor7@gmail.com', '이지후', 'KOREA',
        '안녕하세요! 이지후에요. 저는 사회 현상을 이해하고 분석하는 것에 흥미를 느껴요. 다양한 경제 이슈에 관심을 가지며, 코띠 멘토로 여러분과 소통하며 현실적인 조언과 경제 지식을 공유하고 싶어요.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor7.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-8', 'mentor8@gmail.com', '조승민', 'KOREA',
        '안녕하세요. 저는 한양대 기계공학과에 다니고 있어요. 다양한 프로젝트와 도전을 통해 실무 경험을 쌓고, 이를 통해  여러분과 기술적인 이야기를 공유하며 함께 성장하고 싶어요.',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor8.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-9', 'mentor9@gmail.com', '조승민', 'KOREA',
        '안녕하세요! 인하대학교 화학공학과 23학번 정소윤입니다. 실험과 연구를 통해 다양한 경험을 쌓아오면서, 코띠 멘토로 여러분과 화학 및 공학에 관한 이야기를 나누고 함께 성장하고 싶어요. 🧪🔬',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor9.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR'),
       ('GOOGLE', 'ID-MENTOR-10', 'mentor10@gmail.com', '김은서', 'KOREA',
        '안녕하세요! 저는 한국어뿐만 아니라 영어와 일본어로 소통할 수 있어서 다양한 문화를 즐기며 비즈니스의 다양한 측면을 탐험하고 있어요. 여러분과 인사이트를 공유하고 의미 있는 경험을 함께 만들어 나갔으면 좋겠어요. ',
        'https://koddy-upload.s3.ap-northeast-2.amazonaws.com/dummy-user/mentor10.png',
        1, 'ACTIVE', 'MENTOR', 'MENTOR');

INSERT INTO mentor(id, school, major, entered_in, mentoring_start_date, mentoring_end_date, mentoring_time_unit,
                   school_mail, proof_data_upload_url, auth_status)
VALUES (11, '중앙대학교', '디자인학부(패션전공)', 22, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor1@cau.ac.kr', NULL, 'SUCCESS'),
       (12, '연세대학교', '컴퓨터공학부', 23, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor2@yonsei.ac.kr', NULL, 'SUCCESS'),
       (13, '세종대학교', '건축학과', 22, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor3@sju.ac.kr', NULL, 'SUCCESS'),
       (14, '국민대학교', '시각디자인', 21, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor4@kookmin.ac.kr', NULL, 'SUCCESS'),
       (15, '서강대학교', '심리학', 23, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor5@sogang.ac.kr', NULL, 'SUCCESS'),
       (16, '중앙대학교', '동아시아문화학', 22, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor6@cau.ac.kr', NULL, 'SUCCESS'),
       (17, '전남대학교', '경제학과', 23, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor7@jnu.ac.kr', NULL, 'SUCCESS'),
       (18, '한양대학교', '기계공학과', 23, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor8@hanyang.ac.kr', NULL, 'SUCCESS'),
       (19, '인하대학교', '화학공학과', 22, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor9@inha.ac.kr', NULL, 'SUCCESS'),
       (20, '한국외국어대학교', '경영학과', 23, '2024-01-01', '2025-12-31', 'HALF_HOUR',
        'mentor10@hufs.ac.kr', NULL, 'SUCCESS');

INSERT INTO mentor_schedule(mentor_id, day_of_week, start_time, end_time)
VALUES (11, 'MON', '18:00:00', '23:59:59'),
       (11, 'WED', '18:00:00', '23:59:59'),
       (11, 'THU', '18:00:00', '23:59:59'),
       (12, 'WED', '18:00:00', '20:00:00'),
       (12, 'THU', '18:00:00', '20:00:00'),
       (13, 'SAT', '10:00:00', '22:00:00'),
       (13, 'SUN', '10:00:00', '22:00:00'),
       (14, 'TUE', '12:00:00', '13:00:00'),
       (14, 'WED', '12:00:00', '13:00:00'),
       (14, 'THU', '12:00:00', '13:00:00'),
       (14, 'SAT', '12:00:00', '13:00:00'),
       (15, 'SAT', '13:00:00', '15:00:00'),
       (15, 'SUN', '13:00:00', '15:00:00'),
       (16, 'FRI', '09:00:00', '13:00:00'),
       (16, 'SAT', '09:00:00', '13:00:00'),
       (16, 'SUN', '09:00:00', '13:00:00'),
       (17, 'MON', '11:00:00', '12:00:00'),
       (17, 'TUE', '11:00:00', '12:00:00'),
       (17, 'WED', '11:00:00', '12:00:00'),
       (17, 'THU', '11:00:00', '12:00:00'),
       (17, 'FRI', '11:00:00', '12:00:00'),
       (18, 'SAT', '09:00:00', '14:00:00'),
       (18, 'SUN', '09:00:00', '14:00:00'),
       (19, 'WED', '18:00:00', '22:00:00'),
       (19, 'FRI', '18:00:00', '22:00:00'),
       (19, 'SAT', '18:00:00', '22:00:00'),
       (20, 'TUE', '17:00:00', '19:00:00'),
       (20, 'SUN', '17:00:00', '19:00:00');

INSERT INTO member_language(member_id, language_category, language_type)
VALUES (1, 'VN', 'MAIN'),
       (1, 'KR', 'SUB'),
       (1, 'EN', 'SUB'),
       (2, 'JP', 'MAIN'),
       (2, 'KR', 'SUB'),
       (2, 'EN', 'SUB'),
       (3, 'CN', 'MAIN'),
       (3, 'EN', 'SUB'),
       (4, 'EN', 'MAIN'),
       (5, 'JP', 'MAIN'),
       (5, 'KR', 'SUB'),
       (6, 'VN', 'MAIN'),
       (6, 'EN', 'SUB'),
       (7, 'EN', 'MAIN'),
       (7, 'KR', 'SUB'),
       (8, 'EN', 'MAIN'),
       (8, 'KR', 'SUB'),
       (9, 'JP', 'MAIN'),
       (9, 'EN', 'SUB'),
       (10, 'CN', 'MAIN'),
       (10, 'EN', 'SUB'),
       (11, 'KR', 'MAIN'),
       (11, 'EN', 'SUB'),
       (12, 'KR', 'MAIN'),
       (12, 'EN', 'SUB'),
       (12, 'JP', 'SUB'),
       (13, 'KR', 'MAIN'),
       (13, 'EN', 'SUB'),
       (13, 'CN', 'SUB'),
       (14, 'KR', 'MAIN'),
       (14, 'EN', 'SUB'),
       (15, 'KR', 'MAIN'),
       (15, 'EN', 'SUB'),
       (15, 'JP', 'SUB'),
       (16, 'KR', 'MAIN'),
       (16, 'EN', 'SUB'),
       (16, 'VN', 'SUB'),
       (17, 'KR', 'MAIN'),
       (17, 'EN', 'SUB'),
       (18, 'KR', 'MAIN'),
       (18, 'EN', 'SUB'),
       (18, 'JP', 'SUB'),
       (19, 'KR', 'MAIN'),
       (19, 'EN', 'SUB'),
       (19, 'JP', 'SUB'),
       (20, 'KR', 'MAIN'),
       (20, 'EN', 'SUB'),
       (20, 'JP', 'SUB');
