version: "3"
services:
  redis: # redis-cli
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data/data:/data"
    command: redis-server --requirepass koddy --port 6379
