version: "3"
services:
  database: # mysql -u root -p -> 1234
    image: mysql:8.0.33
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "koddy"
      TZ: "Asia/Seoul"
      LANG: "C.UTF_8"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - "./mysql_data:/var/lib/mysql" # .idb = Table Data / .frm = Table Definition / ...
    networks:
      - koddy-network

networks:
  koddy-network:
    external: true
